name: Deploy Laravel to EC2

on:
  push:
    branches:
      - dev # Trigger deployment on pushes to 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Laravel Sail on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.233.93.90 << 'EOF'
            if [ ! -d "/home/ubuntu/my-cicd" ]; then
              cd /home/ubuntu
              git clone https://github.com/dhammadeep/my-cicd.git
            fi
            cd /home/ubuntu/my-cicd
            git pull origin dev
            composer update
            ./vendor/bin/sail down
            ./vendor/bin/sail up
            ./vendor/bin/sail artisan migrate --force
            ./vendor/bin/sail artisan config:cache
          EOF
